auth_enabled: false
server:
  http_listen_port: 3100

storage_config:
  filesystem:
    directory: /loki/chunks 

schema_config:
  configs:
    - from: 2020-10-24
      store: boltdb-shipper
      object_store: filesystem
      schema: v11