receivers:
  otlp:
    protocols:
      grpc:
        endpoint: localhost:4317
      http:
        endpoint: localhost:4318

processors:
  batch:
    send_batch_size: 1000
    timeout: 10s

exporters:
  debug:
    verbosity: basic

  prometheus:
    endpoint: "localhost:9090"

  loki:
    endpoint: "http://loki:3100/loki/api/v1/push"

  otlphttp:
    endpoint: "http://tempo:3200"
    tls:
      insecure: true

service:
  telemetry:
    metrics:
      address: 0.0.0.0:8888
      
  pipelines:
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheus, debug]

    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [loki, debug]

    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlphttp, debug]