global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "otel-collector"
    static_configs:
      - targets: ["otel-collector:4317"]
  - job_name: "app"
    static_configs:
      - targets: ["app:8080"]
  - job_name: "tempo"
    static_configs:
      - targets: ["tempo:3200"]
  - job_name: "loki"
    static_configs:
      - targets: ["loki:3100"]